addSbtPlugin("com.geirsson"              % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.19")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly" % "0.14.9")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.13")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"    % "1.3.4")
